name: dev-bootstrap
description: Bla bla.
dev_path: devOps
role: project
status: active
tags:
  - setup
language: python
setup:
  - poetry run dev
env:
services: []
depends_on: []
workspace: []
update_strategy: []
priority: []